### ISSUE TITLE
question about class 'PMMLTransformer'

### ISSUE THREAD

**Issue by zhuzhujulie** [jpmml/jpmml-evaluator-spark#32]
hi dear author,
thank you for your project and it really helps me .
i'm a new hand to spark and pmml, and i can't find the class 'PMMLTransformer' used in class 'Transformer', could you please tell me where can i find the class of 'PMMLTranformer'?

**Comment by vruusmann** [comment]
> Could you please tell me where can i find the class of 'PMMLTranformer'?

Most JPMML-Evaluator-Spark classes are written in Java, and reside inside the `src/main/java` directory:
https://github.com/jpmml/jpmml-evaluator-spark/tree/master/src/main/java/org/jpmml/evaluator/spark

However, the `org.jpmml.evaluator.PMMLTransformer` class is written in Scala (kindly donated by Interset Software, Inc.) and resides inside the `src/main/scala` directory:
https://github.com/jpmml/jpmml-evaluator-spark/tree/master/src/main/scala/org/jpmml/evaluator/spark
https://github.com/jpmml/jpmml-evaluator-spark/blob/master/src/main/scala/org/jpmml/evaluator/spark/PMMLTransformer.scala
