### ISSUE TITLE
question about build error

### ISSUE THREAD

**Issue by zhuzhujulie** [jpmml/jpmml-evaluator-spark#33]
hi dear author,
i build this maven project and it has error in generation of 'scala-compile-first' , it says "can't find value DatasetUtil", it also can't find these classes used in PMMLTransformer.scala but defined in java class.  do you know why , i don't know how to fix it , please help me

**Comment by vruusmann** [comment]
> i build this maven project and it has error in generation of 'scala-compile-first'

The Apache Maven build should be fine. At least it is reproducible in a 3rd party Travis CI environment:
https://travis-ci.org/jpmml/jpmml-evaluator-spark

This leads me to believe that you have locally changed something about the build/project, which makes it broken.

> do you know why

Incorrect classpath.
