### ISSUE TITLE
dependency version not consistent

### ISSUE THREAD

**Issue by zhuzhujulie** [jpmml/jpmml-evaluator-spark#35]
hi dear author, thank you for taking time to answer my question.
 whar do you mean of "fix my classpath", my local jdk is verson8 and in spark the jdk is also version8, is there any other things i need to fix? i still can't fix this problem ,
another question is , i read your read.md , i think maybe i can use your maven repository 1.2.2 jar release to construct my project ranther than using your jar code directly, but i dont't understand your code. for example, what does the class "LoadingModelEvaluatorBuilder" come from?
in fact i don't know how to keep the jar version consistently of my local environment and spark environment, can you tell my some metods?

**Comment by zhuzhujulie** [comment]
you said the jar version is not consistent wit two jvms. so how to keep the jar of "jpmml-evaluator" consistent

**Comment by vruusmann** [comment]
This issue has been definitely fixed by now.
