### ISSUE TITLE
when i only use jpmml-evaluator-spark, it will incur an exception

### ISSUE THREAD

**Issue by zdkzdk** [jpmml/jpmml-evaluator-spark#38]
when i only use jpmml-evaluator-spark，it will incur an exception.i must explicitly use the other 2 dependencies.
--------------------error!!!----------------
 <dependency>
            <groupId>org.jpmml</groupId>
            <artifactId>jpmml-evaluator-spark</artifactId>
            <version>1.2.2</version>
        </dependency>
-------------------correct, i have to use 2 extra dependencies!!!----------------------
<dependency>
            <groupId>org.jpmml</groupId>
            <artifactId>jpmml-evaluator-spark</artifactId>
            <version>1.2.2</version>
        </dependency>
        <dependency>
            <groupId>org.jpmml</groupId>
            <artifactId>pmml-evaluator</artifactId>
            <version>1.4.7</version>
        </dependency>
        <dependency>
            <groupId>org.jpmml</groupId>
            <artifactId>pmml-model</artifactId>
            <version>1.4.8</version>
        </dependency>

**Comment by vruusmann** [comment]
What's your Apache Spark version, how are you using the JPMML-Evaluator-Spark library (as part of Apache Maven build, or as a "soft dependency" using the `--packages` command-line option).

I checked the `pom.xml`, and it doesn't use any exclusions (that would cause some dependencies to be left out).

**Comment by zdkzdk** [comment]
spark2.2.0，Apache Maven build
this is my pom,why i have to take 2 extra dependencies: pmml-evaluator and pmml-model

        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-mllib_${scala_spark.version}</artifactId>
            <version>${spark.version}</version>
            <scope>${provided.scope}</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.jpmml</groupId>
                    <artifactId>pmml-model</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        
        <dependency>
            <groupId>org.jpmml</groupId>
            <artifactId>jpmml-evaluator-spark</artifactId>
            <version>1.2.2</version>
        </dependency>
        <dependency>
            <groupId>org.jpmml</groupId>
            <artifactId>pmml-evaluator</artifactId>
            <version>1.4.7</version>
        </dependency>
        <dependency>
            <groupId>org.jpmml</groupId>
            <artifactId>pmml-model</artifactId>
            <version>1.4.8</version>
        </dependency>

another problem,my company is a bank that don't allow networking,so how do I use maven shade,Can shade be used without maven?
Thank you first ~~~

**Comment by vruusmann** [comment]
This issue has been definitely fixed by now.
