### ISSUE TITLE
reading pmml from hdfs

### ISSUE THREAD

**Issue by dagdelenmustafa** [jpmml/jpmml-evaluator-spark#39]
hi i am trying to read my pmml file from hdfs but java.io.InputStream class is searching file from local storage so i get file not found exception. Is there a way to read pmml file from hdfs ?

**Comment by vruusmann** [comment]
> Is there a way to read pmml file from hdfs?

This question should be posted to some Hadoop support forum, not here.

Perhaps you can construct a `java.net.URL` pointing to your HDFS file, and then obtain a `java.io.InputStream` (that you can pass to `LoadingModelEvaluatorBuilder`) via the `URL#openStream()` method.
