### ISSUE TITLE
How to get the functionname of PMML model？

### ISSUE THREAD

**Issue by hjfrank1991** [jpmml/jpmml-evaluator-spark#40]
When I have a PMML file, how do I get the functionname? I can't find the relevant API
i want know which value
<xs:simpleType name="MINING-FUNCTION">
  <xs:restriction base="xs:string">
    <xs:enumeration value="associationRules"/>
    <xs:enumeration value="sequences"/>
    <xs:enumeration value="classification"/>
    <xs:enumeration value="regression"/>
    <xs:enumeration value="clustering"/>
    <xs:enumeration value="timeSeries"/>
    <xs:enumeration value="mixed"/>
  </xs:restriction>
</xs:simpleType>

**Comment by hjfrank1991** [comment]
<RegressionModel functionName="classification" normalizationMethod="softmax">
        <MiningSchema>
            <MiningField name="label" usageType="target"/>
            <MiningField name="message"/>
        </MiningSchema>
        <Output>
            <OutputField name="pmml(prediction)" optype="categorical" dataType="string" isFinalResult="false"/>
            <OutputField name="prediction" optype="continuous" dataType="double" feature="transformedValue">
                <MapValues outputColumn="data:output" dataType="double">
                    <FieldColumnPair field="pmml(prediction)" column="data:input"/>
                    <InlineTable>
                        <row>
                            <data:input>A020901</data:input>
                            <data:output>0</data:output>
                        </row>
                        <row>
                            <data:input>A020304</data:input>
                            <data:output>1</data:output>
                        </row>
                        <row>
                            <data:input>A010903</data:input>
                            <data:output>2</data:output>
                        </row>
                        <row>
                            <data:input>A020204</data:input>
                            <data:output>3</data:output>
                        </row>
                        <row>
                            <data:input>A011603</data:input>
                            <data:output>4</data:output>
                        </row>
                        <row>
                            <data:input>A011504</data:input>
                            <data:output>5</data:output>
                        </row>
                    </InlineTable>
                </MapValues>
            </OutputField>
            <OutputField name="probability(A020901)" optype="continuous" dataType="double" feature="probability" value="A020901"/>
            <OutputField name="probability(A020304)" optype="continuous" dataType="double" feature="probability" value="A020304"/>
            <OutputField name="probability(A010903)" optype="continuous" dataType="double" feature="probability" value="A010903"/>
            <OutputField name="probability(A020204)" optype="continuous" dataType="double" feature="probability" value="A020204"/>
            <OutputField name="probability(A011603)" optype="continuous" dataType="double" feature="probability" value="A011603"/>
            <OutputField name="probability(A011504)" optype="continuous" dataType="double" feature="probability" value="A011504"/>
        </Output>

**Comment by vruusmann** [comment]
First, obtain the underlying `org.jpmml.evaluator.Evaluator` instance via `org.jpmml.evaluator.spark.PMMLTransformer#getEvaluator()`. Then invoke `Evaluator#getMiningFunction()`.
