### ISSUE TITLE
org.jpmml.evaluator.UnsupportedFeatureException (at or around line 30): GeneralRegressionModel

### ISSUE THREAD

**Issue by celamb4** [jpmml/jpmml-evaluator-spark#7]
Hi,

We are trying to evaluate a PMML model in spark which has a general regression (glm) algorithm. However, when implementing as documented in the readme we are unable to evaluate the model against the dataframe. We are able to run and evaluate the PMML with the JPMML-evaluator-example but fails with the jpmml-spark-evaluator.

This works so assuming pmml syntax is correct:
> java -cp example-1.3-SNAPSHOT.jar org.jpmml.evaluator.EvaluationExample --model sample_pmml.pmml --input PMML_Dummy_Data.csv --output output.csv

GLM line which gets called out in stderr:
` <GeneralRegressionModel modelName="General_Regression_Model" modelType="generalizedLinear" functionName="classification" algorithmName="glm" distribution="binomial" linkFunction="logit">`

The following fails when submitted as a spark job

> spark-submit --master yarn --deploy-mode cluster --class com.mapr.examples.SparkSQLHiveContextExample SparkSQLExample-1.0-SNAPSHOT-jar-with-dependencies.jar

CODE:
```

package com.mapr.examples;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.lang.reflect.Method;
import java.util.List;
import org.apache.commons.io.IOUtils;
import org.apache.spark.ml.Transformer;
import org.apache.spark.sql.Dataset;
import org.apache.spark.sql.SparkSession;
import org.jpmml.evaluator.Evaluator;
import org.jpmml.evaluator.InputField;
import org.jpmml.evaluator.ModelEvaluatorFactory;
import org.jpmml.evaluator.spark.EvaluatorUtil;
import org.jpmml.evaluator.spark.TransformerBuilder;

public class SparkSQLHiveContextExample {

	public static void main(String[] args) throws Exception {

		String warehouseLocation = "spark-warehouse";

		SparkSession spark = SparkSession.builder().appName("PMML").config("spark.sql.warehouse.dir", warehouseLocation)
				.enableHiveSupport().getOrCreate();

		File pmmlFile = new File("some_pmml.pmml");
		ClassLoader loader = Thread.currentThread().getContextClassLoader();
		Evaluator evaluator = EvaluatorUtil.createEvaluator(pmmlFile);
		List<InputField> inputFields = evaluator.getInputFields();
		TransformerBuilder pmmlTransformerBuilder = new TransformerBuilder(evaluator)
				.withTargetCols()
				.withOutputCols()
				.exploded(false);

		Transformer pmmlTransformer = pmmlTransformerBuilder.build();

		Dataset<org.apache.spark.sql.Row> sqlDF = spark.sql(
				"SELECT pmml_col_1, pmml_col_2, pmml_col_3, pmml_col_4, pmml_col_5 from pmml_sample");

		Dataset<org.apache.spark.sql.Row> output = pmmlTransformer.transform(sqlDF);

		output.createOrReplaceTempView("pmml_output");
	}


}
```

STDERR trace:
> Log Type: stderr
> Log Upload Time: Fri Jun 23 22:20:26 +0000 2017
> Log Length: 6574
> Showing 4096 bytes of 6574 total. Click here for the full log.
> ewModelEvaluator(ModelEvaluatorFactory.java:126)
>                 at org.jpmml.evaluator.ModelEvaluatorFactory.newModelEvaluator(ModelEvaluatorFactory.java:66)
>                 at org.jpmml.evaluator.spark.EvaluatorUtil.createEvaluator(EvaluatorUtil.java:63)
>                 at org.jpmml.evaluator.spark.EvaluatorUtil.createEvaluator(EvaluatorUtil.java:47)
>                 at com.mapr.examples.SparkSQLHiveContextExample.main(SparkSQLHiveContextExample.java:47)
>                 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>                 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>                 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>                 at java.lang.reflect.Method.invoke(Method.java:498)
>                 at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:637)
> 17/06/23 22:20:25 INFO ApplicationMaster: Final app status: FAILED, exitCode: 15, (reason: User class threw exception: org.jpmml.evaluator.UnsupportedFeatureException (at or around line 30): GeneralRegressionModel)
> 17/06/23 22:20:25 ERROR ApplicationMaster: Uncaught exception:
> org.apache.spark.SparkException: Exception thrown in awaitResult:
>                 at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:194)
>                 at org.apache.spark.deploy.yarn.ApplicationMaster.runDriver(ApplicationMaster.scala:401)
>                 at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:254)
>                 at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$main$1.apply$mcV$sp(ApplicationMaster.scala:766)
>                 at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:67)
>                 at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:66)
>                 at java.security.AccessController.doPrivileged(Native Method)
>                 at javax.security.auth.Subject.doAs(Subject.java:422)
>                 at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1866)
>                 at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:66)
>                 at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:764)
>                 at org.apache.spark.deploy.yarn.ApplicationMaster.main(ApplicationMaster.scala)
> Caused by: org.jpmml.evaluator.UnsupportedFeatureException (at or around line 30): GeneralRegressionModel
>                 at org.jpmml.evaluator.ModelEvaluatorFactory.newModelEvaluator(ModelEvaluatorFactory.java:126)
>                 at org.jpmml.evaluator.ModelEvaluatorFactory.newModelEvaluator(ModelEvaluatorFactory.java:66)
>                 at org.jpmml.evaluator.spark.EvaluatorUtil.createEvaluator(EvaluatorUtil.java:63)
>                 at org.jpmml.evaluator.spark.EvaluatorUtil.createEvaluator(EvaluatorUtil.java:47)
>                 at com.mapr.examples.SparkSQLHiveContextExample.main(SparkSQLHiveContextExample.java:47)
>                 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>                 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>                 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>                 at java.lang.reflect.Method.invoke(Method.java:498)
>                 at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:637)
> 17/06/23 22:20:25 INFO ApplicationMaster: Unregistering ApplicationMaster with FAILED (diag message: User class threw exception: org.jpmml.evaluator.UnsupportedFeatureException (at or around line 30): GeneralRegressionModel)

**Comment by vruusmann** [comment]
The JPMML-Evaluator-Spark is a thin wrapper around the JPMML-Evaluator API. It doesn't add or remove any functionality by itself.

Could it be that you're using greatly different JPMML-Evaluator versions on both sides?

Does the error persist, if you replace `1.3.6` with `1.3-SNAPSHOT` here:
https://github.com/jpmml/jpmml-evaluator-spark/blob/master/pom.xml#L8

Then, rebuild the JPMML-Evaluator-Spark project, and in your application project depend on the newly produced `org.jpmml:jpmml-evaluator-spark:1.1-SNAPSHOT` artifact.

> Caused by: org.jpmml.evaluator.UnsupportedFeatureException (at or around line 30): GeneralRegressionModel
at org.jpmml.evaluator.ModelEvaluatorFactory.newModelEvaluator(ModelEvaluatorFactory.java:126)

Looking at line ModelEvaluatorFactory:126 indicates that the Java `instanceof` operator failed to detect your model object as an instance of `org.dmg.pmml.general_regression.GeneralRegressionModel`:
https://github.com/jpmml/jpmml-evaluator/blob/master/pmml-evaluator/src/main/java/org/jpmml/evaluator/ModelEvaluatorFactory.java#L79
https://github.com/jpmml/jpmml-evaluator/blob/master/pmml-evaluator/src/main/java/org/jpmml/evaluator/ModelEvaluatorFactory.java#L126

How is it possible? In your Java runtime environment, are you using any class file manipulation tools that may be renaming or relocating class files?

What is the actual class name of your general regression model object? Replace `throw new UnsupportedFeatureException(model)` with `throw new IllegalArgumentException(model.getClass().getName())` and find out!

**Comment by vruusmann** [comment]
The problem is that your Spark application classpath (`SparkSQLExample-1.0-SNAPSHOT-jar-with-dependencies.jar`) is not correctly configured. In brief, your application sees JPMML-Model version 1.2.X that is bundled with Apache Spark, not JPMML-Model version 1.3.X that is the transitive dependency of the JPMML-Evaluator-Spark library.

In JPMML-Model 1.2.X the `GeneralRegressionModel` element is mapped to Java class `org.dmg.pmml.GeneralRegressionModel`, whereas in JPMML-Model 1.3.X it is mapped to `org.dmg.pmml.general_regression.GeneralRegressionModel` (note the added `general_regression` package level). This explains why the `(model instanceof org.dmg.pmml.general_regression.GeneralRegressionModel)` check is failing - it's not the same class.

You can solve this issue by packaging your Spark application properly. Alternatively, you may tweak your Apache Spark configuration, and completely remove the two offending JPMML-Model 1.2.X JAR files. See here: https://issues.apache.org/jira/browse/SPARK-15526
